### ISSUE TITLE
I'm wonderring how 

### ISSUE THREAD

**Issue by skironDotNet** [lulworm/bitcedi#1]
Bitcedi is a fork of XDN, so how are you going to sync with updates of XDN? like recent hard forks?
As soon as you update by coping their changes you'll "destroy" mining pool because XDN team who ever they are they don't update pool software for recent HF

If you are not going to follow XDN, then you have fairly dead coin, because what's new about Bitcedi?

**Comment by lulworm** [comment]
We are not copying XDN codes so no need to worry about hard fork. 
What has really happened with XDN is their merge mining update which affected pool but pool administrators have even fix this issue so i don't see where this update can affect us if we should use some codes from XDN.
